version: "3.8"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - 80:3000
    volumes:
      - ./data:/data
    command: npm run start 