version: "3.8"

services:
  next:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.local
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - ./data:/data
    command: npm run dev
  
  sqliteweb:
    image: tomdesinto/sqliteweb
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
    command: /data/props.db